# [START gke_k8s_ksa_serviceaccount_whereami_ksa]
apiVersion: v1
kind: ServiceAccount
metadata:
 labels:
   app: whereami
 name: whereami
 annotations:
   iam.gke.io/gcp-service-account: whereami-sa@${PROJECT_ID}.iam.gserviceaccount.com
# [END gke_k8s_ksa_serviceaccount_whereami_ksa]
---